# Generated by Django 4.2.5 on 2025-04-26 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('continent', models.CharField(blank=True, choices=[('Africa', 'Africa'), ('North America', 'North America'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('South America', 'South America')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('politics', 'Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('tech', 'Tech'), ('fashion', 'Fashion'), ('health', 'Health'), ('travel', 'Travel'), ('education', 'Education'), ('culture', 'Culture'), ('news', 'News'), ('finance', 'Finance'), ('startup', 'Startup'), ('crypto', 'Cryptocurrency'), ('automobile', 'Automobile'), ('food', 'Food'), ('career', 'Career'), ('art', 'Art'), ('parenting', 'Parenting'), ('relationship', 'Relationship')], max_length=50, null=True)),
                ('public_figure', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('interests', models.ManyToManyField(blank=True, to='user_auth.interest')),
            ],
        ),
        migrations.CreateModel(
            name='ComposeNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('media', models.FileField(blank=True, null=True, upload_to='news_media/')),
                ('is_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composed_news', to='user_auth.newsuser')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user_auth.composenews')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='user_auth.composenews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='user_auth.newsuser')),
            ],
            options={
                'unique_together': {('user', 'original_news')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='user_auth.composenews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='user_auth.newsuser')),
            ],
            options={
                'unique_together': {('user', 'news')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='user_auth.composenews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='user_auth.newsuser')),
            ],
            options={
                'unique_together': {('user', 'news')},
            },
        ),
    ]
