# Generated by Django 4.2.5 on 2025-06-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsUser',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='composenews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='composenews',
            name='in_reply_to',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='news',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='retweet',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='original_news',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='ComposeNews',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Retweet',
        ),
    ]
