# Generated by Django 4.2.5 on 2025-01-11 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Leaderboard', 'Leaderboard'), ('Inline', 'Inline Content'), ('Home', 'Home-Inline'), ('Sidebar', 'Sidebar Ad')], max_length=20)),
                ('link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paragraph_positions', models.JSONField(default=list)),
                ('image_large', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_image_large', to=settings.FILER_IMAGE_MODEL)),
                ('image_small', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_image_small', to=settings.FILER_IMAGE_MODEL)),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_video', to='filer.file')),
            ],
        ),
    ]
