# Generated by Django 5.0.6 on 2024-09-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='paragraph_positions',
            field=models.JSONField(default=list),
        ),
    ]
