# Generated by Django 5.0.6 on 2024-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_adbanner_paragraph_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='category',
            field=models.CharField(choices=[('Leaderboard', 'Leaderboard'), ('Inline', 'Inline Content'), ('Home', 'Home-Inline'), ('Sidebar', 'Sidebar Ad')], max_length=20),
        ),
    ]
