# Generated by Django 5.0.6 on 2024-12-18 12:59

import django.db.models.deletion
import file_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name'], 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file_manager.models.upload_to),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='file_manager.folder'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('folder', 'name')},
        ),
    ]
