# Generated by Django 4.2.5 on 2025-01-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_image'),
        ('file_manager', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
