# Generated by Django 4.2.5 on 2025-01-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
