# Generated by Django 4.2.5 on 2025-04-04 13:01

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blog', '0011_remove_blogpost_image_blogmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_images', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.DeleteModel(
            name='BlogMedia',
        ),
    ]
