# Generated by Django 5.0.6 on 2024-08-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_is_shared_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_shared_facebook',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_shared_twitter',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_shared_whatsapp',
        ),
    ]
