# Generated by Django 5.0.6 on 2024-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_subscription_name_alter_subscription_date_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
