# Generated by Django 4.2.5 on 2025-04-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
