# Generated by Django 4.2.5 on 2025-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
