# Generated by Django 5.0.6 on 2024-09-02 18:43

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_is_deleted_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
