# Generated by Django 4.2.5 on 2025-04-05 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blogpost_image_blogmedia_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
