# Generated by Django 5.0.6 on 2024-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_video_date_alter_video_description_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='original_date',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(),
        ),
    ]
