# Generated by Django 4.2.5 on 2025-04-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_storymedia_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymedia',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
