# Generated by Django 4.2.5 on 2025-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_storymedia_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
