# Generated by Django 4.2.5 on 2025-04-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogpost_tweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='blog.category'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
