# Generated by Django 5.0.6 on 2024-09-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
