# Generated by Django 4.2.5 on 2025-05-17 09:49

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blog', '0023_remove_blogpost_tweeted_blogpost_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_seo_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
