# Generated by Django 4.2.5 on 2025-05-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_blogpost_seo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trend',
        ),
    ]
