# Generated by Django 5.0.6 on 2024-12-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_blogpost_image'),
        ('file_manager', '0002_alter_file_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_images', to='file_manager.file'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_videos', to='file_manager.file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_files', to='file_manager.file'),
        ),
    ]
