# Generated by Django 5.0.6 on 2024-12-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_trend_image_alter_trend_video_and_more'),
        ('file_manager', '0002_alter_file_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='video',
        ),
        migrations.AddField(
            model_name='trend',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_file', to='file_manager.file'),
        ),
    ]
