# Generated by Django 5.0.6 on 2024-11-24 18:16

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_rating_productmedia_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
